backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: src/assets
public_folder: ../../assets/

collections:
  - name: "pages"
    label: "Pages"
    description: >
      Where you can edit pages.
    # folder: "src/markdowns/home"
    editor:
      preview: false
    files:
      - file: "src/markdowns/home/index.md"
        name: "index"
        label: "Home"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "home",
            }
          - {
              label: "About",
              name: "about",
              widget: "object",
              fields:
                [
                  { label: "Name", name: "name", widget: "string" },
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Body", name: "body", widget: "markdown" },
                ],
            }
          - {
              label: "Overview",
              name: "overview",
              widget: "object",
              fields: [{ label: "Body", name: "body", widget: "markdown" }],
            }
          - label: "Experiences"
            name: "experiences"
            widget: "list"
            fields:
              - { label: "Date", name: "date", widget: "string" }
              - {
                  label: "Company",
                  name: "company",
                  widget: "object",
                  fields:
                    [
                      { label: "Name", name: "name", widget: "string" },
                      {
                        label: "Link",
                        name: "link",
                        widget: "string",
                        required: false,
                      },
                    ],
                }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }
              - label: "Stacks"
                name: "stacks"
                widget: "list"
                fields:
                  - {
                      label: "Stack Name",
                      name: "stack name",
                      widget: "string",
                    }
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - {
                  label: "Hidden",
                  name: "hidden",
                  widget: "boolean",
                  default: false,
                  hint: "Toggle to hide this project from the website",
                }
              - {
                  label: "Image",
                  name: image,
                  widget: image,
                  choose_url: false,
                }
              - { label: "Title", name: "title", widget: "string" }
              - {
                  label: "Link",
                  name: "link",
                  widget: "string",
                  required: false,
                }
              - { label: "Body", name: "body", widget: "markdown" }
              - label: "Stacks"
                name: "stacks"
                widget: "list"
                fields:
                  - {
                      label: "Stack Name",
                      name: "stack name",
                      widget: "string",
                    }
          - label: "Socials"
            name: "socials"
            widget: "list"
            fields:
              - {
                  label: "Image",
                  name: image,
                  widget: image,
                  choose_url: false,
                }
              - { label: "Title", name: "title", widget: "string" }
              - {
                  label: "Link",
                  name: "link",
                  widget: "string",
                  required: false,
                }
          - label: "Footer"
            name: "footer"
            widget: "object"
            fields:
              [
                { label: "Name", name: "name", widget: "string", required: false, hidden: true },
                { label: "Body", name: "body", widget: "markdown" },
              ]
